In [4]:
pip install xgboost

   ---------------------------------------- 0.0/124.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/124.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/124.9 MB 660.6 kB/s eta 0:03:10
   ---------------------------------------- 0.1/124.9 MB 1.2 MB/s eta 0:01:44
   ---------------------------------------- 0.5/124.9 MB 3.3 MB/s eta 0:00:38
   ---------------------------------------- 0.8/124.9 MB 4.0 MB/s eta 0:00:32
   ---------------------------------------- 1.1/124.9 MB 4.9 MB/s eta 0:00:26
    --------------------------------------- 1.7/124.9 MB 5.9 MB/s eta 0:00:22
    --------------------------------------- 2.1/124.9 MB 6.3 MB/s eta 0:00:20
    --------------------------------------- 2.5/124.9 MB 6.6 MB/s eta 0:00:19
    --------------------------------------- 2.9/124.9 MB 6.5 MB/s eta 0:00:19
   - -------------------------------------- 3.6/124.9 MB 7.3 MB/s eta 0:00:17
   - -------------------------------------- 4.2/124.9 MB 7.9 MB/s eta 0:00:1

In [44]:
import numpy as np
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import classification_report
import warnings

warnings.filterwarnings('ignore')

In [8]:
X,y = make_classification(n_samples=1000,n_features=10,n_informative=2,n_redundant=8,weights=[0.9,0.1],flip_y=0,random_state=42)

np.unique(y,return_counts=True)

(array([0, 1]), array([900, 100], dtype=int64))

In [9]:
X.shape

(1000, 10)

In [15]:
X[:4]

array([[-2.33224581, -1.73015228, -4.05388142, -0.12314825,  1.45550642,
         2.64413143, -2.13427539,  0.85612326, -3.13555024,  1.22003574],
       [ 0.78663065,  0.72655494,  1.07774555, -0.13147735, -0.37843728,
        -0.75308876,  0.76129801, -0.32878979,  0.66469403, -0.32691647],
       [ 1.4709666 ,  1.32562619,  2.08216446, -0.20592975, -0.73362032,
        -1.4402617 ,  1.41403229, -0.60558465,  1.33361742, -0.63083993],
       [-1.4228983 , -1.23404964, -2.11184151,  0.14081466,  0.74760586,
         1.44001517, -1.35384009,  0.5722858 , -1.42261973,  0.63876895]])

In [11]:
y.shape

(1000,)

In [14]:
y[:4]

array([0, 1, 1, 0])

In [17]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=42,stratify=y)


In [18]:
params = {
    "solver":"lbfgs",
    "max_iter":1000,
    "multi_class":"auto",
    "random_state":8888
}

lr = LogisticRegression(**params)

lr.fit(X_train,y_train)

y_pred = lr.predict(X_test)



In [20]:
y_pred, y_test

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 

In [23]:
report = classification_report(y_test,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.95      0.97      0.96       270
           1       0.62      0.50      0.56        30

    accuracy                           0.92       300
   macro avg       0.79      0.73      0.76       300
weighted avg       0.91      0.92      0.92       300



In [25]:
rep_dict = classification_report(y_test,y_pred,output_dict=True)
rep_dict

{'0': {'precision': 0.9456521739130435,
  'recall': 0.9666666666666667,
  'f1-score': 0.9560439560439561,
  'support': 270.0},
 '1': {'precision': 0.625,
  'recall': 0.5,
  'f1-score': 0.5555555555555556,
  'support': 30.0},
 'accuracy': 0.92,
 'macro avg': {'precision': 0.7853260869565217,
  'recall': 0.7333333333333334,
  'f1-score': 0.7557997557997558,
  'support': 300.0},
 'weighted avg': {'precision': 0.9135869565217392,
  'recall': 0.92,
  'f1-score': 0.9159951159951161,
  'support': 300.0}}

In [32]:
rep_dict['macro avg']['f1-score']

{'precision': 0.7853260869565217,
 'recall': 0.7333333333333334,
 'f1-score': 0.7557997557997558,
 'support': 300.0}

In [26]:
import mlflow

In [36]:
mlflow.set_experiment('Venky Experiment')

mlflow.set_tracking_uri("http://127.0.0.1:5000/")

with mlflow.start_run():
    mlflow.log_params(params)
    mlflow.log_metrics(
        {
            'accuracy':rep_dict['accuracy'],
            'recall_class_0': rep_dict['0']['recall'],
            'recall_class_1': rep_dict['1']['recall'],
            'f1_score_macro_avg':rep_dict['macro avg']['f1-score']            
        }
    )
    mlflow.sklearn.log_model(lr,'Logistic Regression')

2024/10/09 11:23:25 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2024/10/09 11:23:25 INFO mlflow.tracking._tracking_service.client: 🏃 View run rebellious-sow-959 at: http://127.0.0.1:5000/#/experiments/843616138958872295/runs/b9fc4d2a32674173ac3df50a3fd2e5ca.
2024/10/09 11:23:25 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/843616138958872295.


# 1. Logistic Regression

In [45]:
log_Reg = LogisticRegression(C=1,solver='liblinear')
log_Reg.fit(X_train,y_train)
y_pred_log_reg = log_Reg.predict(X_test)
print(y_pred_log_reg[:5])
print(y_test[:5])
print(classification_report(y_test,y_pred_log_reg))


[0 0 0 0 0]
[0 0 0 0 0]
              precision    recall  f1-score   support

           0       0.95      0.96      0.95       270
           1       0.60      0.50      0.55        30

    accuracy                           0.92       300
   macro avg       0.77      0.73      0.75       300
weighted avg       0.91      0.92      0.91       300



# 2. Random Forest

In [46]:
rfc = RandomForestClassifier(n_estimators=30,criterion='gini',max_depth=3)
rfc.fit(X_train,y_train)
y_pred_rfc = rfc.predict(X_test)
print(y_pred_rfc[:5])
print(y_test[:5])
print(classification_report(y_test,y_pred_rfc))


[0 0 0 0 0]
[0 0 0 0 0]
              precision    recall  f1-score   support

           0       0.96      1.00      0.98       270
           1       0.95      0.67      0.78        30

    accuracy                           0.96       300
   macro avg       0.96      0.83      0.88       300
weighted avg       0.96      0.96      0.96       300



# 3. XGBoost

In [47]:
xgb = XGBClassifier(use_label_encoder = False,eval_metric = 'logloss')
xgb.fit(X_train,y_train)
y_pred_xgb = xgb.predict(X_test)
print(y_pred_xgb[:5])
print(y_test[:5])
print(classification_report(y_test,y_pred_xgb))

[0 0 0 0 0]
[0 0 0 0 0]
              precision    recall  f1-score   support

           0       0.98      1.00      0.99       270
           1       0.96      0.80      0.87        30

    accuracy                           0.98       300
   macro avg       0.97      0.90      0.93       300
weighted avg       0.98      0.98      0.98       300



In [55]:
pip install --upgrade scikit-learn imbalanced-learn


   ---------------------------------------- 0.0/258.3 kB ? eta -:--:--
   ---- ----------------------------------- 30.7/258.3 kB 1.4 MB/s eta 0:00:01
   ------------------------------------ --- 235.5/258.3 kB 3.6 MB/s eta 0:00:01
   ---------------------------------------- 258.3/258.3 kB 2.7 MB/s eta 0:00:00
  Attempting uninstall: imbalanced-learn
    Found existing installation: imbalanced-learn 0.11.0
    Uninstalling imbalanced-learn-0.11.0:
      Successfully uninstalled imbalanced-learn-0.11.0
Note: you may need to restart the kernel to use updated packages.


In [57]:
import sklearn
import imblearn

print("scikit-learn version:", sklearn.__version__)
print("imbalanced-learn version:", imblearn.__version__)


scikit-learn version: 1.5.2
imbalanced-learn version: 0.12.4


# 4. Handle Class imbalance using SMOTETomek and then train using XGBoost

In [58]:
from imblearn.combine import SMOTETomek

smt = SMOTETomek(random_state=42)
X_train_res,y_train_res = smt.fit_resample(X_train,y_train)

np.unique(y_train_res,return_counts=True)

(array([0, 1]), array([619, 619], dtype=int64))

In [60]:
xgb_cf = XGBClassifier(use_label_encoder=False,eval_metric='logloss')
xgb_cf.fit(X_train_res,y_train_res)
y_pred_xgb_cf = xgb_cf.predict(X_test)
print(classification_report(y_test,y_pred_xgb_cf))


              precision    recall  f1-score   support

           0       0.98      0.98      0.98       270
           1       0.81      0.83      0.82        30

    accuracy                           0.96       300
   macro avg       0.89      0.91      0.90       300
weighted avg       0.96      0.96      0.96       300



# Track Experiments using MLFlow

In [61]:
models = [
(
    "Logistic Regression",
    LogisticRegression(C=1,solver='liblinear'),
    (X_train,y_train),
    (X_test,y_test)
),
    
(
    "Random Forest",
    RandomForestClassifier(n_estimators=30,criterion='gini',max_depth=3),
    (X_train,y_train),
    (X_test,y_test)
),

(
    "XGB Classifier",
    XGBClassifier(use_label_encoder=False,eval_metric='logloss'),
    (X_train,y_train),
    (X_test,y_test)
),

(
    "XGB Classifier with SMOTE",
    XGBClassifier(use_label_encoder=False,eval_metric='logloss'),
    (X_train_res,y_train_res),
    (X_test,y_test)
)

]

In [62]:
models

[('Logistic Regression',
  LogisticRegression(C=1, solver='liblinear'),
  (array([[ 1.18673836,  1.51144074,  0.78490373, ..., -0.61229492,
           -0.13830257, -0.24753395],
          [-1.28810271, -1.03855344, -2.07092052, ...,  0.49607021,
           -1.50376955,  0.62474155],
          [ 1.66393774,  1.55142135,  2.25024183, ..., -0.69955586,
            1.36600648, -0.68290518],
          ...,
          [ 0.43101615,  0.90013637, -0.42606094, ..., -0.32069604,
           -1.01508454,  0.11782042],
          [ 0.79839935,  1.5003473 , -0.45098948, ..., -0.54728572,
           -1.42140103,  0.11944858],
          [ 0.67367695,  1.27538516, -0.39960348, ..., -0.464427  ,
           -1.22522394,  0.10635794]]),
   array([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
          0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [74]:
reports =[]

for model_info in models:
    print(model_info[0])


Logistic Regression
Random Forest
XGB Classifier
XGB Classifier with SMOTE


In [81]:
reports =[]
for model_name,model,train_data,test_data in models:
    print('LEN IS ',len(train_data[0]))
    print('LEN IS ',len(test_data[0]))
    X_train = train_data[0]
    y_train = train_data[1]
    X_test = test_data[0]
    y_test = test_data[1]

    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    report = classification_report(y_test,y_pred,output_dict=True)
    reports.append(report)
    
    

LEN IS  700
LEN IS  300
LEN IS  700
LEN IS  300
LEN IS  700
LEN IS  300
LEN IS  1238
LEN IS  300


In [82]:
reports

[{'0': {'precision': 0.9454545454545454,
   'recall': 0.9629629629629629,
   'f1-score': 0.9541284403669725,
   'support': 270.0},
  '1': {'precision': 0.6,
   'recall': 0.5,
   'f1-score': 0.5454545454545454,
   'support': 30.0},
  'accuracy': 0.9166666666666666,
  'macro avg': {'precision': 0.7727272727272727,
   'recall': 0.7314814814814814,
   'f1-score': 0.749791492910759,
   'support': 300.0},
  'weighted avg': {'precision': 0.9109090909090909,
   'recall': 0.9166666666666666,
   'f1-score': 0.91326105087573,
   'support': 300.0}},
 {'0': {'precision': 0.9676258992805755,
   'recall': 0.9962962962962963,
   'f1-score': 0.9817518248175182,
   'support': 270.0},
  '1': {'precision': 0.9545454545454546,
   'recall': 0.7,
   'f1-score': 0.8076923076923077,
   'support': 30.0},
  'accuracy': 0.9666666666666667,
  'macro avg': {'precision': 0.961085676913015,
   'recall': 0.8481481481481481,
   'f1-score': 0.8947220662549129,
   'support': 300.0},
  'weighted avg': {'precision': 0.9663

In [83]:
print(reports)


[{'0': {'precision': 0.9454545454545454, 'recall': 0.9629629629629629, 'f1-score': 0.9541284403669725, 'support': 270.0}, '1': {'precision': 0.6, 'recall': 0.5, 'f1-score': 0.5454545454545454, 'support': 30.0}, 'accuracy': 0.9166666666666666, 'macro avg': {'precision': 0.7727272727272727, 'recall': 0.7314814814814814, 'f1-score': 0.749791492910759, 'support': 300.0}, 'weighted avg': {'precision': 0.9109090909090909, 'recall': 0.9166666666666666, 'f1-score': 0.91326105087573, 'support': 300.0}}, {'0': {'precision': 0.9676258992805755, 'recall': 0.9962962962962963, 'f1-score': 0.9817518248175182, 'support': 270.0}, '1': {'precision': 0.9545454545454546, 'recall': 0.7, 'f1-score': 0.8076923076923077, 'support': 30.0}, 'accuracy': 0.9666666666666667, 'macro avg': {'precision': 0.961085676913015, 'recall': 0.8481481481481481, 'f1-score': 0.8947220662549129, 'support': 300.0}, 'weighted avg': {'precision': 0.9663178548070633, 'recall': 0.9666666666666667, 'f1-score': 0.9643458731049971, 'sup

In [91]:
import mlflow
mlflow.set_experiment("Anomoly Detection")
mlflow.set_tracking_uri("http://127.0.0.1:5000/")

for i,element in enumerate(models):
    model_name = element[0]
    model = element[1]
    rep = reports[i]

    with mlflow.start_run(run_name=model_name):
        mlflow.log_param('model_venky',model_name)
        mlflow.log_params(params)
        mlflow.log_metrics(
        {
            'accuracy':rep_dict['accuracy'],
            'recall_class_0': rep_dict['0']['recall'],
            'recall_class_1': rep_dict['1']['recall'],
            'f1_score_macro_avg':rep_dict['macro avg']['f1-score']            
        }        
                          )

        if "XGB" in model_name:
            mlflow.xgboost.log_model(model,"model")
        else:
            mlflow.sklearn.log_model(model,"model")
        

2024/10/09 13:10:08 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2024/10/09 13:10:08 INFO mlflow.tracking._tracking_service.client: 🏃 View run Logistic Regression at: http://127.0.0.1:5000/#/experiments/333417542457804789/runs/46d6a915e8064975871dfdf9dd3c5e37.
2024/10/09 13:10:08 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/333417542457804789.
2024/10/09 13:10:12 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2024/10/09 13:10:12 INFO mlflow.tracking._tracking_service.client: 🏃 View run Random Forest at: http://127.0.0.1:5000/#/experiments/333417542457804789/runs/e4422a46f0fc4727a4acdd24cb7d45f2.
2024/10/09 13:10:12 INFO mlflow.tracking._tracking_service.client: 🧪 View exp

# Include All Params in Model List

In [95]:
models = [
(
    "Logistic Regression",
    {"C":1,"solver":'liblinear'},
    LogisticRegression(),
    (X_train,y_train),
    (X_test,y_test)
),
    
(
    "Random Forest",
    {"n_estimators":30,"criterion":'gini',"max_depth":3},
    RandomForestClassifier(),
    (X_train,y_train),
    (X_test,y_test)
),

(
    "XGB Classifier",
    {"use_label_encoder":False,"eval_metric":'logloss'},
    XGBClassifier(),
    (X_train,y_train),
    (X_test,y_test)
),

(
    "XGB Classifier with SMOTE",
    {"use_label_encoder":False,"eval_metric":'logloss'},
    XGBClassifier(),
    (X_train_res,y_train_res),
    (X_test,y_test)
)

]

In [96]:
reports =[]
for model_name,params,model,train_data,test_data in models:
    X_train = train_data[0]
    y_train = train_data[1]
    X_test = test_data[0]
    y_test = test_data[1]

    model.set_params(**params)
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    report = classification_report(y_test,y_pred,output_dict=True)
    reports.append(report)
    
    

In [97]:
 # Initializing ML flow

import mlflow
mlflow.set_experiment("Anomoly Detection-V2")
mlflow.set_tracking_uri("http://127.0.0.1:5000/")

for i,element in enumerate(models):
    model_name = element[0]
    params_v2 = element[1]
    model = element[2]
    rep = reports[i]

    with mlflow.start_run(run_name=model_name):
        mlflow.log_param('model_venky_v2',model_name)
        mlflow.log_params(params_v2)
        mlflow.log_metrics(
        {
            'accuracy':rep_dict['accuracy'],
            'recall_class_0': rep_dict['0']['recall'],
            'recall_class_1': rep_dict['1']['recall'],
            'f1_score_macro_avg':rep_dict['macro avg']['f1-score']            
        }        
                          )

        if "XGB" in model_name:
            mlflow.xgboost.log_model(model,"model")
        else:
            mlflow.sklearn.log_model(model,"model")
        

2024/10/09 13:49:24 INFO mlflow.tracking.fluent: Experiment with name 'Anomoly Detection-V2' does not exist. Creating a new experiment.
2024/10/09 13:49:28 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2024/10/09 13:49:28 INFO mlflow.tracking._tracking_service.client: 🏃 View run Logistic Regression at: http://127.0.0.1:5000/#/experiments/738113202955647616/runs/2ed1d144d15b4f57af0d8f598ccb3837.
2024/10/09 13:49:28 INFO mlflow.tracking._tracking_service.client: 🧪 View experiment at: http://127.0.0.1:5000/#/experiments/738113202955647616.
2024/10/09 13:49:32 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
2024/10/09 13:49:32 INFO mlflow.tracking._tracking_service.client: 🏃 View run Random Forest at: http://127.0.0.1:5000/#/experiments

## Register Model whichever we need after checking metrics

In [118]:
model_name="XGB-Smote"
run_id =input("enter run id ")
model_uri = f'runs:/{run_id}/{model_name}'


result = mlflow.register_model(
    model_uri,model_name
)


enter run id  7dcb35c63e1e415282a755ae925d4de3


Successfully registered model 'XGB-Smote'.
2024/10/09 15:05:28 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: XGB-Smote, version 1
Created version '1' of model 'XGB-Smote'.


# Load the Model from Registry

In [123]:
model_name = "XGB-Smote"
model_version =1
#model_uri = f"models:/{model_name}/{model_version}"
print(f"model_uri is {model_uri}")

#loaded_model = mlflow.xgboost.load_model(model_uri)

# Later, load the model
model_uri = "models:/XGB-Smote/1"  # Ensure the model and version are correct
loaded_model = mlflow.xgboost.load_model(model_uri)



y_pred = loaded_model.predict(X_test)
y_pred[:5]

model_uri is models:/XGB-Smote/1


MlflowException: The following failures occurred while downloading one or more artifacts from http://localhost:5000/api/2.0/mlflow-artifacts/artifacts/738113202955647616/7dcb35c63e1e415282a755ae925d4de3/artifacts/XGB-Smote:
##### File  #####
API request to http://localhost:5000/api/2.0/mlflow-artifacts/artifacts/738113202955647616/7dcb35c63e1e415282a755ae925d4de3/artifacts/XGB-Smote/ failed with exception HTTPConnectionPool(host='localhost', port=5000): Max retries exceeded with url: /api/2.0/mlflow-artifacts/artifacts/738113202955647616/7dcb35c63e1e415282a755ae925d4de3/artifacts/XGB-Smote/ (Caused by ResponseError('too many 500 error responses'))